image: salamandar/archlinux-gimp:latest

stages:
  - gimp

variables:
  INSTALL_DIR: "_install"
  INSTALL_PREFIX: "${CI_PROJECT_DIR}/${INSTALL_DIR}"
  PACMAN_CACHE:   "${CI_PROJECT_DIR}/_pacman_cache"

cache:
  paths:
  - _pacman_cache


# build-min-autotools:
#   extends: .gimp-autotools
#   dependencies:
#     - babl-git
#     - gegl-git

# build-min-meson:
#   extends: .gimp-meson
#   dependencies:
#     - babl-min
#     - gegl-min
